### ISSUE TITLE
Use symbolic icons

### ISSUE THREAD

**Issue by SeaDve** [Schmiddiii/Tubefeeder#12]
I think it would look better, and more native on pinephone

**Comment by Schmiddiii** [comment]
I took all the icons from [here](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html).
I did not notice that symbolic icons were already installed by default. I will look into that when I have time.

**Comment by SeaDve** [comment]
You just have to append -symbolic to icon name like "list-add" to "list-add-symbolic"

**Comment by Schmiddiii** [comment]
The icons have now been changed to symbolic icons.
Please look at the screenshots on the [symbolic-icons](https://github.com/Schmiddiii/Tubefeeder/tree/symbolic-icons)-branch to
look at them or compile the branch yourself.

Please give feedback or maybe any icons that could be improved.
