### ISSUE TITLE
Appimage/Flatpak for the desktop?

### ISSUE THREAD

**Issue by KristijanZic** [Schmiddiii/Tubefeeder#13]
Please provide an amd64 build for the desktop users.

**Comment by Schmiddiii** [comment]
I have already thought about that. 
Unfortunately I run Ubuntu 18.04, which does not provide libhandy needed to build the application.
Therefor I currently can not compile this application on my laptop.

I have thought about a few solutions, e.g. using docker to compile (using [cross](https://github.com/rust-embedded/cross)), but I think I already tried that and failed.  
Maybe I will try to compile the application on amd once again.

**Comment by SeaDve** [comment]
I recommend on looking at flatpak, while developing, you can package libhandy there no matter your distro

**Comment by Schmiddiii** [comment]
I might look into using flatpak.
I currently know nothing about it so I cannot comment on whether it will work.
I will report back after I looked into that.

**Comment by SeaDve** [comment]
https://gitlab.gnome.org/bilelmoussaoui/gtk-rust-template/-/tree/master/

There's a template

**Comment by Schmiddiii** [comment]
@KristijanZic I have made a working AppImage. Sadly I cannot include the AppImage in the text, so you will have to compile it
yourself. Please try it out.

@SeaDve Maybe I will look into Flatpak in the future, as compiling it was not as hard as I remembered.

**Comment by Schmiddiii** [comment]
I noticed the AppImage could not run mpv on my system.
After failing to repair it, I switched to flatpak.

Flatpak is working on amd64, but I cannot cross compile it. See #16 for more information.
Any help is appreciated.

**Comment by Schmiddiii** [comment]
A flatpak is now available on [flathub](https://flathub.org/apps/details/de.schmidhuberj.tubefeeder).
Please test it out.

I will close this issue, please reopen or create a new issue if needed.
