### ISSUE TITLE
Can't filter a whole youtube channel

### ISSUE THREAD

**Issue by Froggy232** [Schmiddiii/Tubefeeder#165]
Hi,
I try to filter a youtube channel from my home page, but it doesn't work.
If I place a filter with a title option and leave the channel field empty, it works as expected (as it will hide all video with the right title regardless of the origin channel).
If I try to place a filter on a channel with leaving the title field empty, the channel still appear in my homepage.
Is it possible to filter a whole channel?
Thanks you

**Comment by Schmiddiii** [comment]
Works for me. Did you maybe misspell the channel name?

Also note that this GitHub project was moved to [GitLab](https://gitlab.com/schmiddi-on-mobile/pipeline).

**Comment by Froggy232** [comment]
Hi,
Thanks for your answer, I didn't know it was moved to gitlab, sorry for that.
I search a little more, and it seems the problem came from the default API. If I change it to an unofficial one, everything work.
I will make a bug report on the official API, as it seems the problem came from that.
Thanks you again!
