### ISSUE TITLE
Default window size is tiny

### ISSUE THREAD

**Issue by jannuary** [Schmiddiii/Tubefeeder#19]
It seems on desktop, the default window size is set to an unusable value:
![image](https://user-images.githubusercontent.com/27908024/124226682-b3208500-db33-11eb-96fd-004fa42059d5.png)

**Comment by Schmiddiii** [comment]
I can also confirm this issue.
I believe the cause may be the same as with #20 .
See there for more information.

**Comment by Schmiddiii** [comment]
I have mad a pull request regarding this issue.
Could you please comment on how big the window should be.

You can find out the current size of a window by typing `xwininfo` into the terminal and clicking the window.
In the output of the command there will be `Width` and `Height`.
