### ISSUE TITLE
Using GTK3 Settings for font sizes

### ISSUE THREAD

**Issue by codeandcreate** [Schmiddiii/Tubefeeder#2]
Currently the base font sizes are hard coded; `n * pango::SCALE`.
It would be better to use the current GTK3 / session settings to scale the font based on user preferences.

**Comment by Schmiddiii** [comment]
I agree that this should probably not be hardcoded. The main problem I see is that this application uses two different font sizes (e.g. one for the video title and one for the channel). How should I handle the two different font sizes? Should I make it a fixed amount smaller than from the settings?

**Comment by codeandcreate** [comment]
i would successt to use something like `n * 0.75 * pango::SCALE.` for the smaller font... maybe with some rounding :)

**Comment by Schmiddiii** [comment]
I have implemented this feature in a new branch. Please check it out.
Note that you cannot change the font size using `settings.ini` on wayland. For more information look at the pull request.

**Comment by codeandcreate** [comment]
Works for me! i use following code in .config/sway/config to set font size (...):

exec /usr/libexec/gsd-xsettings
exec lxpolkit
exec gsettings set org.gnome.desktop.interface font-name 'Inter Regular 15'
exec gsettings set org.gnome.desktop.interface monospace-font-name 'Hack Regular 15'

imho the small font is a little bit too small... but i'm using a fullhd screen with 12" and no scaling ;) so i think it is alright.
a little hint; add some spacing in feed_item.rs: 
[feed_item.rs_diff.txt](https://github.com/Schmiddiii/Tubefeeder/files/6292013/feed_item.rs_diff.txt)

![screenshot-2021-04-11-16-36-28](https://user-images.githubusercontent.com/22428204/114308450-60ab6b80-9ae4-11eb-854d-6c0df696740f.png)

**Comment by Schmiddiii** [comment]
Added the spacing, thanks for the suggestion.
I am not that good with nice looking gui :slightly_smiling_face:.

**Comment by codeandcreate** [comment]
If you want i can help you with ui things when you will continue development :)  just mail me anytime.
