### ISSUE TITLE
Headerbar is undraggable and has no close button

### ISSUE THREAD

**Issue by jannuary** [Schmiddiii/Tubefeeder#20]
On desktop, the headerbar is lacking window control buttons (such as close, maximize, minimize), and the window cannot be dragged by dragging the headerbar.

**Comment by Schmiddiii** [comment]
Can confirm.
I just used a window manager to test the flatpak on the desktop, which scaled it and has no header bar at default.
I will look into that.

One question I have is how did you install the application? Flatpak, AppImage or compiled it yourself?

**Comment by jannuary** [comment]
Flatpak.
