### ISSUE TITLE
Hi, is it possible to insert Subscriptions

### ISSUE THREAD

**Issue by ralf1307** [Schmiddiii/Tubefeeder#5]
Hi, is it possible to insert Subscriptions or generally control the program with an another program/script.
 
As search results also include channels I would like to give the channel-id to your app or db, as I don't want to deal with fetching channel-uploads over and over again.

P.S.: I would love to open youtube-videos inside my app, as my app can search and play videos. Is there some preferred way you want to open a video in my app? (I would think of an argument while launching my app) 

(Im sending a link of my app as soon as its able to play videos again, im currently rewritting my backend library for yt and want to adjust for gtk4)

**Comment by Schmiddiii** [comment]
> Hi, is it possible to insert Subscriptions or generally control the program with an another program/script. 

You can subscribe to a channel by appending the wanted ID into `subscriptions.db`.
Note that this will only update the application after a restart.

I do not know what you mean with `generally control`. You might be able to simulate mouse clicks but that is all.

> P.S.: I would love to open youtube-videos inside my app, as my app can search and play videos. Is there some preferred way you want to open a video in my app? (I would think of an argument while launching my app)

This is currently not possible, but can be easily changed by changing `mpv` to your desired video player in `src/youtube_feed/feed.rs` in line 289.
Introducing a argument for this is currently not what I am planing, as `mpv` seems to be the only video player, that is able to play youtube videos and has a interface where everything is accessible (e.g. VLC shows most controlls offscreen and therefore can not be used). I might make such feature in the future if more video players support such a low screen resolution.
